# All lights
- alias: Turn On All Lights at Sunset
  trigger:
  - event: sunset
    offset: -0:30
    platform: sun
  action:
  - data:
      entity_id: group.all_lights
      brightness: 255
    service: homeassistant.turn_on

# Inside lights
- alias: Activate Sleeping at Sleep Time
  trigger:
  - platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.sleep_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  action:
  - data:
      entity_id: input_boolean.sleeping
    service: input_boolean.turn_on

- alias: Turn off some lights at Sleeping
  trigger:
  - platform: state
    entity_id: input_boolean.sleeping
    to: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.sleeping

# Sunrise
- alias: Turn All Off at Sunrise
  trigger:
  - event: sunrise
    offset: +01:30
    platform: sun
  action:
  - data:
      entity_id: group.all_lights
    service: homeassistant.turn_off
  - data:
      entity_id: input_boolean.sleeping
    service: input_boolean.turn_off

# Night light
- alias: Turn Night Lights On by Motion Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_3
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action:
  - data:
      entity_id: 
        - switch.plug_4
    service: homeassistant.turn_on
- alias: Turn Night Lights Off Automatically
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_3
      to: 'off'
      for: "00:05:00"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '00:10:00'
      - condition: sun
        before: sunrise
  action:
  - data:
      entity_id: 
        - switch.plug_4
    service: homeassistant.turn_off

# Dimmer
- alias: Dimmer On
  trigger:
    platform: state
    entity_id: sensor.tradfri_wireless_dimmer_battery_level
  condition:
    condition: template
    value_template: "{{ trigger.to_state.state|int != 0 }}"
  action:
    - service: light.turn_on
      entity_id: light.light_1
      data_template:
        brightness: "{{ trigger.to_state.state|int }}"
    - service: light.turn_on
      entity_id: light.light_2
      data_template:
        brightness: "{{ trigger.to_state.state|int }}"

# Detect presence
- alias: Turn Off Away On Motion Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_3
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.away
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: 
        - input_boolean.away
  - service: persistent_notification.create
    data: 
      title: "Motion"
      message: "Presence detected, away mode turned OFF"
- alias: Turn On Away After No Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_3
      to: 'off'
      for: "08:00:00"
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - input_boolean.away
  - service: persistent_notification.create
    data: 
      title: "No motion"
      message: "No presence, away mode turned ON"
- alias: Turn On Away Automatically
  trigger:
    - platform: time
      at: "12:00:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away
        state: 'off'
      - condition: template
        value_template: "{{ as_timestamp(now()) - as_timestamp(states.binary_sensor.tradfri_motion_sensor_3.last_changed) > 21600 }}"
        # 21600 = 6h ago
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - input_boolean.away
  - service: persistent_notification.create
    data: 
      title: "No motion"
      message: "It's mid day and still no presence, away mode turned ON"

# Low indoor temperature
# - alias: Low Temperature Alert
#   trigger:
#     platform: template
#     value_template: "{{ state_attr('climate.steninge', 'current_temperature') < states('input_number.min_temp_threshold') }}"