
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Https settings
http:
  server_port: 8123
  ssl_certificate: /config/fullchain.pem
  ssl_key: /config/privkey.pem

# System log
system_log:
  max_entries: 100

# Logger
logger:
  default: info
  logs:
    homeassistant.components.switch: critical

# Logbook
logbook:
  exclude:
    entities:
      - device_tracker.hixs
      - device_tracker.hi6s
      - device_tracker.mmbp
      - device_tracker.ms10
      - sensor.date
      - sensor.time
    domains:
      - switch

# Notify
notify:
  - platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret email_sender
    encryption: starttls
    username: !secret email_username
    password: !secret email_password
    recipient: !secret email_recipient
    sender_name: My Home Assistant
    
    
# notify:
#   - platform: html5
#     vapid_pub_key: !secret vapid_pub_key
#     vapid_prv_key: !secret vapid_prv_key
#     vapid_email: !secret vapid_email

# Text to speech
tts:
  - platform: google_translate

# Time and uptime
sensor:
  - platform: time_date
    display_options:
      - 'time'
  - platform: uptime
    name: Uptime
    unit_of_measurement: days

# Ping
device_tracker:
  - platform: ping
    consider_home: 300
    hosts:
      hi6s: !secret hi6s_ip
      hixs: !secret hixs_ip
      mmbp: !secret mmbp_ip
      ms10: !secret ms10_ip

# Sensibo
climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key

# Google Assistant
google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  exposed_domains:
    - light
  entity_config:
    group.all_automations:
      expose: false
    light.tradfri_wireless_dimmer_2:
      expose: false
    input_boolean.sleeping:
      expose: true
    input_datetime.sleep_time:
      expose: true

# Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
#input_select: !include input_select.yaml

# Inputs
input_boolean:
  bed_1:
    name: Sovrummet
    initial: off
    icon: mdi:bed-empty
  bed_2:
    name: Blå rummet
    initial: on
    icon: mdi:bed-empty
  bed_3:
    name: Helenas rum
    initial: on
    icon: mdi:bed-empty
  bed_4:
    name: Biblioteket
    initial: off
    icon: mdi:bed-empty
  sleeping:
    name: Sovläge
    initial: off
    icon: mdi:sleep
  away:
    name: Bortaläge
    initial: on
    icon: mdi:car-side

input_datetime:
  sleep_time:
    name: Sovtid
    has_date: false
    has_time: true
    initial: '23:45'

input_number:
  min_temp_threshold:
    name: Lägsta temperatur
    initial: 17
    min: 15
    max: 25
    step: 0.25

# Light switches
light:
  - platform: switch
    name: Altanen
    entity_id: switch.plug_1
  - platform: switch
    name: Biblioteket
    entity_id: switch.plug_2
  - platform: switch
    name: Vardagsrummet
    entity_id: switch.plug_3
  - platform: switch
    name: Hallen
    entity_id: switch.plug_4
  - platform: switch
    name: Helenas rum
    entity_id: switch.plug_5
  - platform: switch
    name: Blå rummet
    entity_id: switch.plug_6
  - platform: switch
    name: Sovrummet
    entity_id: switch.plug_7

# Scenes
scene:
  - name: Day
    entities:
      group.all_lights:
        state: false
  - name: Evening
    entities:
      group.all_lights:
        state: true
        brightness: 255
  - name: Evening Away
    entities:
      group.all_lights:
        state: true
        brightness: 255
  - name: Sleeping
    entities:
      script.sleeping_scene:
        state: true
  - name: Sleeping Away
    entities:
      script.sleeping_away_scene:
        state: true