# Core config
homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  name: !secret name
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Https settings
http:
  server_port: 8123
  ssl_certificate: /ssl/fullchain1.pem
  ssl_key: /ssl/privkey1.pem
  base_url: !secret base_url

# System log
system_log:
  max_entries: 100

# Logger
logger:
  default: info
  logs:
    homeassistant.components.switch: critical

# Logbook
logbook:
  exclude:
    entities:
      - device_tracker.hixs
      - device_tracker.hi6s
      - device_tracker.mmbp
      - device_tracker.ms10
      - sensor.date
      - sensor.time
    domains:
      - switch

# HACS
hacs:
  token: !secret hacs_token

# Notify
notify:
  - name: email
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret email_sender
    encryption: starttls
    username: !secret email_username
    password: !secret email_password
    recipient: !secret email_recipient
    sender_name: My Home Assistant
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
    
    
# notify:
#   - platform: html5
#     vapid_pub_key: !secret vapid_pub_key
#     vapid_prv_key: !secret vapid_prv_key
#     vapid_email: !secret vapid_email

# Text to speech
tts:
  - platform: google_translate

sensor:
  # Time and uptime
  - platform: time_date
    display_options:
      - 'time'
  - platform: uptime
    name: Uptime
    unit_of_measurement: days
  
  # Temperature
  - platform: template
    sensors: 
      indoor_temperature:
        value_template: '{{ states.climate.steninge.attributes.current_temperature|float }}'  
        friendly_name: 'Inomhustemp' 
        unit_of_measurement: '°C'
  - platform: template
    sensors: 
      outdoor_temperature:
        value_template: '{{ states.weather.steninge.attributes.temperature|float }}'  
        friendly_name: 'Utomhustemp' 
        unit_of_measurement: '°C'
  - platform: template
    sensors: 
      set_temperature:
        value_template: '{{ states.climate.steninge.attributes.temperature|float }}'  
        friendly_name: 'Inställd temp' 
        unit_of_measurement: '°C'

# Humidity
  - platform: template
    sensors: 
      indoor_humidity:
        value_template: '{{ states.climate.steninge.attributes.current_humidity|float }}'  
        friendly_name: 'Fuktighet inne' 
        unit_of_measurement: '%'
  - platform: template
    sensors: 
      outdoor_humidity:
        value_template: '{{ states.weather.steninge.attributes.humidity|float }}'  
        friendly_name: 'Fuktighet ute' 
        unit_of_measurement: '%'

# CPU Temp
  - platform: command_line
    name: CPU Temp
    command: "/bin/cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "ºC"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

# System monitor
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: network_in
      arg: wlan0
    - type: network_out
      arg: wlan0
    - type: throughput_network_in
      arg: wlan0
    - type: throughput_network_out
      arg: wlan0

# Ping
device_tracker:
  - platform: ping
    consider_home: 300
    hosts:
      hi6s: !secret hi6s_ip
      hixs: !secret hixs_ip
      mmbp: !secret mmbp_ip
      ms10: !secret ms10_ip
      jipa: !secret jipa_ip
      eiph: !secret eiph_ip
      aiph: !secret aiph_ip

# Sensibo
climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

# Google Assistant
google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  exposed_domains:
    - light
  entity_config:
    group.all_automations:
      expose: false
    light.tradfri_wireless_dimmer_2:
      expose: false
    input_boolean.sleeping:
      expose: true
    input_datetime.sleep_time:
      expose: true
    switch.plug_9:
      expose: true

# Spotify
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

# Spotcast
spotcast:
  username: !secret spotify_username
  password: !secret spotify_password

# Includes
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
input_select: !include includes/input_select.yaml
input_boolean: !include includes/input_boolean.yaml
input_datetime: !include includes/input_datetime.yaml
input_number: !include includes/input_number.yaml
input_text: !include includes/input_text.yaml
light: !include includes/light.yaml
scene: !include includes/scene.yaml