
homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  name: !secret name
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Https settings
http:
  server_port: 8123
  ssl_certificate: /config/fullchain.pem
  ssl_key: /config/privkey.pem

# System log
system_log:
  max_entries: 100

# Logger
logger:
  default: info
  logs:
    homeassistant.components.switch: critical

# Logbook
logbook:
  exclude:
    entities:
      - device_tracker.hixs
      - device_tracker.hi6s
      - device_tracker.mmbp
      - device_tracker.ms10
      - sensor.date
      - sensor.time
    domains:
      - switch

# Notify
notify:
  - name: email
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret email_sender
    encryption: starttls
    username: !secret email_username
    password: !secret email_password
    recipient: !secret email_recipient
    sender_name: My Home Assistant
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
    
    
# notify:
#   - platform: html5
#     vapid_pub_key: !secret vapid_pub_key
#     vapid_prv_key: !secret vapid_prv_key
#     vapid_email: !secret vapid_email

# Text to speech
tts:
  - platform: google_translate

# Time and uptime
sensor:
  - platform: time_date
    display_options:
      - 'time'
  - platform: uptime
    name: Uptime
    unit_of_measurement: days

# Ping
device_tracker:
  - platform: ping
    consider_home: 300
    hosts:
      hi6s: !secret hi6s_ip
      hixs: !secret hixs_ip
      mmbp: !secret mmbp_ip
      ms10: !secret ms10_ip
      jipa: !secret jipa_ip
      eiph: !secret eiph_ip
      aiph: !secret aiph_ip

# Sensibo
climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

# Google Assistant
google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  exposed_domains:
    - light
  entity_config:
    group.all_automations:
      expose: false
    light.tradfri_wireless_dimmer_2:
      expose: false
    input_boolean.sleeping:
      expose: true
    input_datetime.sleep_time:
      expose: true

# Includes
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
#input_select: !include includes/input_select.yaml
input_boolean: !include includes/input_boolean.yaml
input_datetime: !include includes/input_datetime.yaml
input_number: !include includes/input_number.yaml
light: !include includes/light.yaml
scene: !include includes/scene.yaml