# Altandimmer
- alias: Dimmer up Altan
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_wireless_dimmer
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - group.outside_lights
          - light.bulb_4
        brightness: >
          {% set bri = state_attr('light.bulb_1', 'brightness') | int %}
          {{ [bri+30, 255] | min }}

- alias: Dimmer down Altan
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_wireless_dimmer
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - group.outside_lights
          - light.bulb_4
        brightness: >
          {% set bri = state_attr('light.bulb_1', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

# On/off dimmer
- alias: Dimmer up On/off
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_on_off_switch
      event: 1001
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - group.outside_lights
          - light.bulb_4
        brightness: >
          {% set bri = state_attr('light.bulb_1', 'brightness') | int %}
          {{ [bri+30, 255] | min }}

- alias: Dimmer down On/off
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_on_off_switch
      event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - group.outside_lights
          - light.bulb_4
        brightness: >
          {% set bri = state_attr('light.bulb_1', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

- alias: Dimmer on On/off
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_on_off_switch
      event: 1002
  action:
    - service: scene.turn_on
      entity_id: scene.evening
    - service: homeassistant.turn_off
      data:
        entity_id: 
          - input_boolean.sleeping

- alias: Dimmer off On/off
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_on_off_switch
      event: 2002
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: 
          - input_boolean.sleeping