# Dimmer
- alias: 'Dimmer up'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_wireless_dimmer
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.bulb_1
          - light.bulb_2
          - light.bulb_4
        brightness: >
          {% set bri = state_attr('light.bulb_1', 'brightness') | int %}
          {{ [bri+30, 255] | min }}

- alias: 'Dimmer down'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_wireless_dimmer
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.bulb_1
          - light.bulb_2
          - light.bulb_4
        brightness: >
          {% set bri = state_attr('light.bulb_1', 'brightness') | int %}
          {{ [bri-30, 0] | max }}