# Dimmer
- alias: Dimmer On
  trigger:
    platform: state
    entity_id: sensor.altandimmer_battery_level
  action:
    - service: light.turn_on
      entity_id: light.bulb_1
      data_template:
        brightness: "{{ 255 / 100 * states('sensor.altandimmer_battery_level')|int }}"
    - service: light.turn_on
      entity_id: light.bulb_2
      data_template:
        brightness: "{{ 255 / 100 *  states('sensor.altandimmer_battery_level')|int }}"