# Hall on/off dimmer
- alias: Hall dimmer up
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_4
        event: 1001
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.nya_hallen
        brightness: >
          {% set bri = state_attr('light.nya_hallen', 'brightness') | int %}
          {{ [bri+75, 255] | min }}

- alias: Hall dimmer down
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_4
        event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.nya_hallen
        brightness: >
          {% set bri = state_attr('light.nya_hallen', 'brightness') | int %}
          {{ [bri-75, 0] | max }}

# Button press up
- alias: Hall dimmer on
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_4
        event: 1002
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.nya_hallen
        brightness_pct: 100 

# Button press down
- alias: Hall dimmer off
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_4
        event: 2002
  action:
    - service: light.turn_off
      data_template:
        entity_id: 
          - light.nya_hallen
