# Altandimmer
#- alias: Dimmer up Altan
#  initial_state: 'on'
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: tradfri_wireless_dimmer
#      event: 2002
#  action:
#    - service: light.turn_on
#      data_template:
#        entity_id: 
#          - light.outside_lights
#          - light.koket
#        brightness: >
#          {% set bri = state_attr('light.altan_gavel', 'brightness') | int %}
#          {{ [bri+30, 255] | min }}

#- alias: Dimmer down Altan
#  initial_state: 'on'
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: tradfri_wireless_dimmer
#      event: 3002
#  action:
#    - service: light.turn_on
#      data_template:
#        entity_id: 
#          - light.outside_lights
#          - light.koket
#        brightness: >
#          {% set bri = state_attr('light.altan_gavel', 'brightness') | int %}
#          {{ [bri-30, 0] | max }}

# House on/off dimmer (1 and 2)
- alias: House dimmer up
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_1
        event: 1001
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_2
        event: 1001
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.outside_lights
          - light.koket
        brightness: >
          {% set bri = state_attr('light.altan_gavel', 'brightness') | int %}
          {{ [bri+30, 255] | min }}

- alias: House dimmer down
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_1
        event: 2001
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_2
        event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.outside_lights
          - light.koket
        brightness: >
          {% set bri = state_attr('light.altan_gavel', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

# Button press up
- alias: House dimmer on
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_1
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_2
        event: 1002
  action:
    - service: homeassistant.turn_on
      data_template:
        entity_id: >
          {% if is_state('input_boolean.evening', 'on') %}
            script.scene_all_on
          {% else %}
            script.scene_evening
          {% endif %}
    - service: homeassistant.turn_off
      data:
        entity_id: 
          - input_boolean.sleeping

# Button press down
- alias: House dimmer off
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_1
        event: 2002
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_2
        event: 2002
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: 
          - input_boolean.sleeping
    - service: homeassistant.turn_on
      data_template:
        entity_id: >
          {% if is_state('input_boolean.sleeping', 'on') %}
            script.scene_day
          {% else %}
            input_boolean.sleeping
          {% endif %}
