# Night light
- alias: Night Lights On by Motion Detected
  trigger:
    - platform: state
      entity_id: group.motion_sensors
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - switch.plug_4
  - service: homeassistant.turn_on
    data_template:
      entity_id: >
        {% if is_state('input_boolean.bright_night_light', 'on') %}
          script.scene_all_on
        {% else %}
          light.bulb_8
        {% endif %}
  - service: logbook.log
    data_template:
      name: Motion
      message: was detected, night light turned ON
      entity_id: group.motion_sensors

- alias: Night Lights Off Automatically
  trigger:
    - platform: state
      entity_id: group.motion_sensors
      to: 'off'
      for: "00:05:00"
  condition:
    condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - script.scene_sleeping
  - service: logbook.log
    data_template:
      name: No motion
      message: was detected, night light turned OFF
      entity_id: group.motion_sensors

# Morning light
- alias: Morning Lights On by Motion Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_2
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '05:00:00'
      - condition: time
        before: '12:00:00'
      - condition: state
        entity_id: input_boolean.sleeping
        state: 'off'
      - condition: template
        value_template: "{{ not is_state('weather.dark_sky' , 'sunny') }}"
  action:
  - data:
      entity_id: 
        - switch.plug_4
        - light.bulb_4
    service: homeassistant.turn_on
  - service: logbook.log
    data_template:
      name: Motion
      message: was detected, not sunny, day light turned ON
      entity_id: binary_sensor.tradfri_motion_sensor_2

- alias: Morning Lights Off Automatically
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_2
      to: 'off'
      for: "00:10:00"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '05:00:00'
      - condition: time
        before: '13:00:00'
      - condition: state
        entity_id: input_boolean.sleeping
        state: 'off'
  action:
  - data:
      entity_id: 
        - switch.plug_4
        - light.bulb_4
    service: homeassistant.turn_off
  - service: logbook.log
    data_template:
      name: No motion
      message: was detected, day light turned OFF
      entity_id: binary_sensor.tradfri_motion_sensor_2
