# Night light
- alias: Turn Night Lights On by Motion Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_2
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action:
  - data:
      entity_id: 
        #- switch.plug_1
        - switch.plug_4
    service: homeassistant.turn_on

- alias: Turn Night Lights Off Automatically
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_2
      to: 'off'
      for: "00:05:00"
  condition:
    condition: state
    entity_id: input_boolean.sleeping
    state: 'on'
  action:
  - data:
      entity_id: 
        #- switch.plug_1
        - switch.plug_4
    service: homeassistant.turn_off