# Office on/off dimmer
- alias: Office dimmer up
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_3
        event: 1001
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.kontor_tak
          - light.kontor_bord
        brightness: >
          {% set bri = state_attr('light.kontor_tak', 'brightness') | int %}
          {{ [bri+50, 255] | min }}

- alias: Office dimmer down
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_3
        event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.kontor_tak
          - light.kontor_bord
        brightness: >
          {% set bri = state_attr('light.kontor_tak', 'brightness') | int %}
          {{ [bri-50, 0] | max }}

# Button press up
- alias: Office dimmer on
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_3
        event: 1002
  action:
    - service: light.turn_on
      data_template:
        entity_id: 
          - light.kontor_tak
          - light.kontor_bord
        brightness_pct: 100
        rgb_color: [255, 200, 145]
    - service: homeassistant.turn_off
      data:
        entity_id: 
          - switch.sonoff1

# Button press down
- alias: Office dimmer off
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: switch_3
        event: 2002
  action:
    - service: light.turn_off
      data_template:
        entity_id: 
          - light.kontor_tak
          - light.kontor_bord
    - service: homeassistant.turn_on
      data:
        entity_id: 
          - switch.sonoff1
