# Office light, conditioned by device tracker MMBP

# Turn Office Light On at Sunset If Working
- alias: Turn Office Light On at Sunset If Working
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition:
    condition: state
    entity_id: device_tracker.mmbp
    state: 'home'
  action:
  - service: light.turn_on
    data:
      entity_id: light.bulb_5
      brightness: 255
      rgb_color: [255,129,1]

# Turn Office Light On when MMBP is On (when sun below horizon)
- alias: Turn Office Light On when MMBP is On 
  trigger:
    - platform: state
      entity_id: device_tracker.mmbp
      to: 'home'
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    data:
      entity_id: light.bulb_5
      brightness: 255
      rgb_color: [255,129,1]
    
# Turn Office Light On when MMBP is Off (when sun below horizon)
- alias: Turn Office Light On when MMBP is Off
  trigger:
    - platform: state
      entity_id: device_tracker.mmbp
      to: 'away'
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_off
    data:
      entity_id: light.bulb_5