# Away
- alias: Turn On Away After No Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_3
      to: 'off'
      for: "08:00:00"
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - input_boolean.away
  - service: persistent_notification.create
    data: 
      title: "No motion"
      message: "No presence for 8h, away mode turned ON"

- alias: Turn On Away Automatically (Backup)
  trigger:
    - platform: time
      at: "12:00:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away
        state: 'off'
      - condition: template
        value_template: "{{ as_timestamp(now()) - as_timestamp(states.binary_sensor.tradfri_motion_sensor_3.last_changed) > 21600 }}"
        # 21600 = 6h ago
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - input_boolean.away
  - service: persistent_notification.create
    data: 
      title: "No motion"
      message: "It's mid day and no presence for, away mode turned ON"


# Detect presence
- alias: Turn Off Away On Presence Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.tradfri_motion_sensor_3
      to: 'on'
    - platform: state
      entity_id: group.all_devices
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.away
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: 
        - input_boolean.away
  - service: persistent_notification.create
    data: 
      title: "Motion"
      message: "Presence (motion or wifi) detected, away mode turned OFF"


# Home again
- alias: Turn Everything On When Home Again
  trigger:
    - platform: state
      entity_id: input_boolean.away
      to: 'off'
  action:
  - service: input_datetime.set_datetime
    data_template:
      entity_id: input_datetime.sleep_time
      time: "23:45"
  - condition: state  # from sunset until sunrise
    entity_id: sun.sun
    state: 'below_horizon'
  - service: scene.turn_on
    entity_id: scene.evening
  - service: persistent_notification.create
    data: 
      title: "Home"
      message: "Welcome home again, turning everything ON!"