# Away
- alias: Away On After No Motion
  trigger:
    - platform: state
      entity_id: group.motion_sensors
      to: 'off'
      for: "04:00:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'away'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - input_boolean.away
  - service: persistent_notification.create
    data: 
      title: "No motion"
      message: "No presence for 4h, away mode turned ON"
  - service: notify.pushbullet
    data:
      title: "Steninge ALERT: No presence 4h"
      message: "No presence for 4h, away mode turned ON"

- alias: Away On Automatically (Backup)
  trigger:
    - platform: time
      at: "12:00:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away
        state: 'off'
      - condition: template
        value_template: "{{ as_timestamp(now()) - as_timestamp(states.binary_sensor.tradfri_motion_sensor_2.last_changed) > 21600 }}"
        # 21600 = 6h ago
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - input_boolean.away
  - service: persistent_notification.create
    data: 
      title: "No motion"
      message: "It's midday and no presence for 6h, away mode turned ON"
  - service: notify.pushbullet
    data:
      title: "Steninge ALERT: No presence midday"
      message: "It's midday and no presence for 6h, away mode turned ON"


# Detect motion
- alias: Away Off On Motion Detected
  trigger:
    - platform: state
      entity_id: group.motion_sensors
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.away
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: 
        - input_boolean.away
  - service: persistent_notification.create
    data: 
      title: "Presence"
      message: "Motion detected, away mode turned OFF"
  - service: notify.pushbullet
    data:
      title: "Steninge ALERT: Presence"
      message: "Motion detected, away mode turned OFF"
  - service: logbook.log
    data_template:
      name: Motion
      message: was detected
      entity_id: group.motion_sensors

# Detected device (wifi)
- alias: Away Off On Wifi Device Detected
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.away
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: 
        - input_boolean.away
  - service: persistent_notification.create
    data: 
      title: "Presence"
      message: "Wifi device detected, away mode turned OFF"
  - service: notify.pushbullet
    data:
      title: "Steninge ALERT: Wifi presence"
      message: "Wifi device detected, away mode turned OFF"
  - service: logbook.log
    data_template:
      name: WIFI
      message: was detected
      entity_id: binary_sensor.tradfri_motion_sensor_2

# Away mode turned off
- alias: Home again
  trigger:
    - platform: state
      entity_id: input_boolean.away
      to: 'off'
  action:
  - service: ifttt.trigger
    data:
      event: "enable_mute"
  - service: input_datetime.set_datetime
    data_template:
      entity_id: input_datetime.sleep_time
      time: "23:45"
  - condition: state  # from sunset until sunrise
    entity_id: sun.sun
    state: 'below_horizon'
  - service: homeassistant.turn_on
    entity_id: script.scene_evening
  - service: persistent_notification.create
    data: 
      title: "Home"
      message: "Welcome home again, turning everything ON!"

# Away mode turned on
- alias: Leaving home
  trigger:
    - platform: state
      entity_id: input_boolean.away
      to: 'on'
  action:
  - service: ifttt.trigger
    data:
      event: "disable_mute"

  # Device specific
- alias: Occupy M bed on detected presence
  trigger:
    - platform: state
      entity_id: device_tracker.ms10
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.bed_2
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.bed_2
  - service: persistent_notification.create
    data: 
      title: "Home"
      message: "Martin is home!"

- alias: Unoccupy M bed on no presence
  trigger:
    - platform: state
      entity_id: device_tracker.ms10
      to: 'away'
      for: "04:00:00"
  condition:
    condition: state
    entity_id: input_boolean.bed_2
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.bed_2

- alias: Occupy H bed on detected presence
  trigger:
    - platform: state
      entity_id: device_tracker.hi6s
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.bed_3
    state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.bed_3
  - service: persistent_notification.create
    data: 
      title: "Home"
      message: "Helena is home!"

- alias: Unoccupy H bed on no presence
  trigger:
    - platform: state
      entity_id: device_tracker.hi6s
      to: 'home'
      for: "04:00:00"
  condition:
    condition: state
    entity_id: input_boolean.bed_3
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.bed_3