- alias: Turn Off Away On Start If Home
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: 
        - input_boolean.away

- alias: Restart message
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: persistent_notification.create
    data: 
      title: "Restart"
      message: "Home Assistant restarted"
  - service: notify.pushbullet
    data:
      title: "Steninge ALERT: Restart"
      message: "Home Assistant restarted"