# Sensibo unavailable
- alias: Sensibo unavailable alert
  trigger:
    platform: template
    value_template: "{{ is_state('climate.steninge', 'unavailable') }}"
  action:
  - service: persistent_notification.create
    data_template:
      title: "Sensibo unavailable"
      message: "Sensibo is currently unavailable"
  - service: notify.pushbullet
    data_template:
      title: "Steninge ALERT: Sensibo"
      message: "Sensibo is currently unavailable"

# Low indoor temperature
- alias: Low Indoor Temperature - Alert and Turn On Heater
  trigger:
    platform: template
    value_template: "{{ state_attr('climate.steninge', 'current_temperature') | float < states('input_number.indoor_low_temp_warning') | float }}"
  condition:
    condition: template
    value_template: "{{ not is_state('climate.steninge', 'unavailable') }}"
  action:
  - service: persistent_notification.create
    data_template:
      title: "Low temperature"
      message: "Indoor temperature {{ state_attr('climate.steninge', 'current_temperature')}} is below the alarm threshold {{ states('input_number.indoor_low_temp_warning') }}"
  - service: notify.pushbullet
    data_template:
      title: "Steninge ALERT: Temperature"
      message: "Indoor temperature {{ state_attr('climate.steninge', 'current_temperature')}} is below the alarm threshold {{ states('input_number.indoor_low_temp_warning') }}"
  - condition: state
    entity_id: climate.steninge
    state: 'off'
  - service: climate.turn_on
    entity_id: climate.steninge

# Low outdoor temperature
- alias: Low Outdoor Temperature (2h) - Start Heater
  trigger:
    platform: template
    value_template: "{{ states('sensor.outdoor_temperature') | float < states('input_number.outdoor_low_temp_threshold') | float }}"
    for: "02:00:00"
  condition:
    condition: state
    entity_id: climate.steninge
    state: 'off'
  action:
  - service: climate.turn_on
    entity_id: climate.steninge

# Acceptable outdoor temperature
- alias: Acceptable Outdoor Temperature (2h) - Stop Heater
  trigger:
    platform: template
    value_template: "{{ states('sensor.outdoor_temperature') | float > states('input_number.outdoor_low_temp_threshold') | float }}"
    for: "02:00:00"
  condition:
    condition: state
    entity_id: climate.steninge
    state: 'on'
  action:
  - service: climate.turn_off
    entity_id: climate.steninge

  # Acceptable indoor temperature
- alias: Acceptable Indoor Temperature (2h) - Stop Heater
  trigger:
    platform: template
    value_template: "{{ state_attr('climate.steninge', 'current_temperature') | float > states('input_number.indoor_low_temp_warning') | float }}"
    for: "02:00:00"
  condition:
    condition: state
    entity_id: climate.steninge
    state: 'on'
  action:
  - service: climate.turn_off
    entity_id: climate.steninge