# Low indoor temperature
- alias: Low Temperature Alert
  trigger:
    platform: template
    value_template: "{{ state_attr('climate.steninge', 'current_temperature') | float < states('input_number.min_temp_threshold') | float }}"
  action:
  - service: persistent_notification.create
    data: 
      title: "Low temperature"
      message: "Indoor temperature is below the alart threshold"
  - service: notify.pushbullet
    data:
      title: "Steninge ALERT: Temperature"
      message: "Indoor temperature is below the alart threshold"