# Wake up
- alias: Wake up at Wake up Time
  trigger:
  - platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.wake_up_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.wake_up_light
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - script.scene_morning
  - delay: '01:15'
  - service: homeassistant.turn_off
    data:
      entity_id: 
        - switch.plug_3
        - switch.plug_8
        - switch.plug_10
        - light.bulb_4
        - light.bulb_7