# Wake up
- alias: Turn on light at Wake up Time
  trigger:
  - platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.wake_up_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.wake_up_light
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - switch.plug_2
  - service: light.turn_on
    data:
      entity_id: light.bulb_5
      brightness: 255
      rgb_color: [255,182,109]
      transition: 30
  - service: homeassistant.turn_off
    data:
      entity_id: input_boolean.sleeping
  - delay: '00:30'
  - service: homeassistant.turn_off
    data:
      entity_id: 
        - switch.plug_2
  - service: light.turn_on
    data:
      entity_id: light.bulb_5
      brightness: 255
      transition: 0