- platform: switch
  name: Uterum
  entity_id: switch.plug_1
- platform: switch
  name: Kontor fönster
  entity_id: switch.plug_2
- platform: switch
  name: Vardagsrum tavla
  entity_id: switch.plug_3
- platform: switch
  name: Gamla hallen
  entity_id: switch.plug_4
- platform: switch
  name: Helenas rum
  entity_id: switch.plug_5
- platform: switch
  name: Blå rummet
  entity_id: switch.plug_6
- platform: switch
  name: Sovrummet
  entity_id: switch.plug_7
- platform: switch
  name: Oanvänd ett
  entity_id: switch.plug_8
- platform: switch
  name: Oanvänd två
  entity_id: switch.plug_10
- platform: group
  name: Office lights
  entities:
    - light.kontor_tak
    - light.kontor_golv
    - light.kontor_bord
    - light.kontor_fonster
- platform: group
  name: Living room lights
  entities:
    - light.vardagsrum_tak
    - light.vardagsrum_golv
    - light.vardagsrum_horn
    - light.vardagsrum_bord
    - light.vardagsrum_tavla
- platform: group
  name: Outside lights
  entities:
    - light.altan_gavel
    - light.altan_vagg
    - light.kontor_gavel
- platform: group
  name: Inside lights
  entities:
    - light.uterum
    - light.bla_rummet
    - light.helenas_rum
    - light.sovrummet
    - light.badrum_fonster
    - light.badrum_bord
    - light.koket
    - light.nya_hallen
    - light.gamla_hallen
    - light.office_lights
    - light.living_room_lights
- platform: group
  name: All lights
  entities:
    - light.uterum
    - light.sovrummet
    - light.bla_rummet
    - light.helenas_rum
    - light.altan_gavel
    - light.altan_vagg
    - light.badrum_fonster
    - light.badrum_bord
    - light.koket
    - light.nya_hallen
    - light.gamla_hallen
    - light.kontor_gavel
    - light.kontor_tak
    - light.kontor_golv
    - light.kontor_bord
    - light.kontor_fonster
    - light.vardagsrum_tak
    - light.vardagsrum_bord
    - light.vardagsrum_golv
    - light.vardagsrum_horn
    - light.vardagsrum_tavla
    # - light.oanvand_ett
    # - light.oanvand_tva