- platform: switch
  name: Uterum
  entity_id: switch.plug_1
- platform: switch
  name: Kontor fönster
  entity_id: switch.plug_2
- platform: switch
  name: Vardagsrum tavla
  entity_id: switch.plug_3
- platform: switch
  name: Gamla hallen
  entity_id: light.gamla_hallen
- platform: switch
  name: Helenas rum
  entity_id: switch.plug_5
- platform: switch
  name: Blå rummet
  entity_id: switch.plug_6
- platform: switch
  name: Sovrummet
  entity_id: switch.plug_7
- platform: switch
  name: Oanvänd ett
  entity_id: switch.plug_8
- platform: switch
  name: Oanvänd två
  entity_id: light.uterum0